language: java
language: kotlin
jdk:
- oraclejdk8
script:
- bash gradlew buildPlugin --info --no-daemon
- bash gradlew verifyPlugin --info --no-daemon
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/