sudo: required
language: java
language: kotlin
jdk:
- oraclejdk8
script:
- ./gradlew displayCommitHash
- ./gradlew isCI
- ./gradlew buildPlugin --info
- ./gradlew verifyPlugin --info
before_install:
- chmod a+x gradlew
